// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiqumuqtzejtiinezryu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpcXVtdXF0emVqdGlpbmV6cnl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzU5NTIsImV4cCI6MjA3MjU1MTk1Mn0.BtS5aCyB0WUjMc1QFdAMLbFuWHb4e_lUBNWIh-3Yrdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});